export type FlexItemProps = {
  width?: string | number;
  height?: string | number;
  flexDirection?: any;
  alignItems?: string;
  justify?: string;
  flexWrap?: any;
  flex?: string | number;
  border?: string;
  borderTop?: string;
  borderBottom?: string;
  borderLeft?: string;
  borderRight?: string;
  background?: string;
  position?: any;
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
  color?: string;
  margin?: string | number;
  padding?: string | number;
  className?: any;
};